server:
  port: 8081

spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/user?serverTimezone=Asia/Seoul
    username: test
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  secret: rlaguswjdtlstkskdnslRKdkswdkdlTdj
  expiration: 31536000000

logging:
  level:
    org:
      springframework:
        security: TRACE