spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  data:
    mongodb:
      uri: mongodb://localhost:27017/productImg
