spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    mongodb:
      uri: mongodb://localhost:27017/productImg?authSource=admin

logging:
    file:
      name: logs/spring.log
    level:
      root: INFO
      org.springframework.web: DEBUG
      graphql: DEBUG