spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: review
          uri: lb://REVIEW
          predicates:
            - Path=/reviews/**

        - id: product-service
          uri: lb://PRODUCT
          predicates:
              - Path=/product/**
              - Method=POST, OPTIONS
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
