spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        # example
        - id: user-service
          uri: lb://USER
          predicates:
            - Path=/auth/**
        # add your service

eureka:
  instance:
    prefer-ip-address: true
