spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        # example
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        # add your service
eureka:
  instance:
    prefer-ip-address: true
