spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        # example
        - id: user-service
          uri: lb://USER
          predicates:
            - Path=/auth/**
        - id: product-service
          uri: lb://PRODUCT
          predicates:
            - Path=/product/**
            - Method=POST, OPTIONS
        # add your service
eureka:
  instance:
    prefer-ip-address: true
