server:
  port: 9010

spring:
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      name: jwt
      profile: default
  application:
    name: reservation-service
  datasource:
    url: jdbc:mysql://localhost:3306/reservation?serverTimezone=Asia/Seoul
    username: root
    password: jung8728

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  expiration: 1000000000
  secret: rlaguswjdtlstkskdnslRKdkswdkdlTdj
#jwt:
#  secret: asdfaerrwesdfserw2asdfaerrwesdfserw2321
#  expiration: 86400000




